apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-iris-app
  labels:
    app: telemetry-iris-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-iris-app
  template:
    metadata:
      labels:
        app: telemetry-iris-app
    spec:
      serviceAccountName: telemetry-access
      containers:
        - name: fastapi-container
          image: us-central1-docker.pkg.dev/my-project-test-iitm-oppe/my-repo/iris-fastapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
          readinessProbe:
            httpGet:
              path: /ready_check
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /live_check
              port: 8200
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
