apiVersion: v1
kind: Service
metadata:
  name: telemetry-iris-app-service
spec:
  selector:
    app: telemetry-iris-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer
